import { useCallback, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Bot, FileAudio, Loader2, Upload, Sparkles, Info, AlertTriangle, BarChart3, Activity } from "lucide-react";
import { AUDIO_ACCEPT, isLikelyAudioFile } from "@/lib/audioFileInput";
import { analyzeForAI, type AISongCheckResult, type Verdict, type ProbBlock } from "@/lib/aiSongCheck";
import SEO from "@/components/SEO";
import Breadcrumbs from "@/components/Breadcrumbs";
import ToolkitHeader from "@/components/tools/ToolkitHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { softwareAppSchema, breadcrumbSchema } from "@/lib/seo/schemas";

const STRINGS = {
  fr: {
    title: "AI Song Checker",
    tagline: "Détectez si un morceau a été généré par une IA — 100% local, aucun upload.",
    dropTitle: "Glissez un fichier audio ici",
    dropSub: "ou cliquez pour parcourir (MP3, WAV, FLAC, M4A, OGG)",
    analyzing: "Analyse acoustique en cours…",
    analyze: "Analyser un autre fichier",
    duration: "Durée",
    seconds: "secondes",
    spectral: "Analyse spectrale",
    temporal: "Analyse temporelle",
    overall: "Verdict global",
    human: "Humain",
    hybrid: "Hybride (IA + Humain)",
    ai: "IA pure",
    invalid: "Fichier audio invalide. Formats acceptés : MP3, WAV, FLAC, M4A, OGG.",
    error: "Erreur lors de l'analyse du fichier.",
    disclaimerTitle: "Méthode et limites",
    disclaimer:
      "Cet outil applique une analyse heuristique locale : variance de planéité spectrale, coupure haute fréquence, corrélation stéréo, régularité des transitoires, micro-dynamique RMS et patterns de silence. Ces marqueurs sont fréquemment associés aux générateurs IA (Suno, Udio, MusicGen…) mais ne constituent pas un classifieur entraîné. Considérez les résultats comme indicatifs : un mastering très propre ou un morceau électronique peut produire des faux positifs.",
    detailsTitle: "Mesures détaillées",
    features: {
      spectralFlatnessMean: "Planéité spectrale moy.",
      spectralFlatnessStd: "Variance de planéité",
      hfCutoffHz: "Coupure HF (Hz)",
      stereoCorrelation: "Corrélation stéréo",
      onsetIntervalCv: "CV inter-transitoires",
      rmsMicroDynamics: "Micro-dynamique RMS (dB)",
      silenceRatio: "Ratio de silence",
    },
    verdicts: {
      very_likely: "très probable",
      likely: "probablement",
      unlikely: "probablement pas",
      very_unlikely: "très peu probable",
    },
  },
  en: {
    title: "AI Song Checker",
    tagline: "Detect if a track was generated by AI — 100% local, no upload.",
    dropTitle: "Drop an audio file here",
    dropSub: "or click to browse (MP3, WAV, FLAC, M4A, OGG)",
    analyzing: "Running acoustic analysis…",
    analyze: "Analyze another file",
    duration: "Duration",
    seconds: "seconds",
    spectral: "Spectral analysis",
    temporal: "Temporal analysis",
    overall: "Overall verdict",
    human: "Human",
    hybrid: "Hybrid (AI + Human)",
    ai: "Pure AI",
    invalid: "Invalid audio file. Accepted formats: MP3, WAV, FLAC, M4A, OGG.",
    error: "Error analyzing file.",
    disclaimerTitle: "Method & limits",
    disclaimer:
      "This tool runs a local heuristic analysis: spectral flatness variance, HF cutoff, stereo correlation, transient regularity, RMS micro-dynamics and silence patterns. These markers are commonly seen in AI generators (Suno, Udio, MusicGen…) but this is NOT a trained classifier. Treat results as indicative — a very clean master or an electronic track can produce false positives.",
    detailsTitle: "Detailed measurements",
    features: {
      spectralFlatnessMean: "Mean spectral flatness",
      spectralFlatnessStd: "Flatness variance",
      hfCutoffHz: "HF cutoff (Hz)",
      stereoCorrelation: "Stereo correlation",
      onsetIntervalCv: "Onset interval CV",
      rmsMicroDynamics: "RMS micro-dynamics (dB)",
      silenceRatio: "Silence ratio",
    },
    verdicts: {
      very_likely: "very likely",
      likely: "likely",
      unlikely: "unlikely",
      very_unlikely: "very unlikely",
    },
  },
};

const verdictColor = (v: Verdict) => {
  switch (v) {
    case "very_likely":
      return "text-red-400";
    case "likely":
      return "text-orange-400";
    case "unlikely":
      return "text-emerald-300";
    case "very_unlikely":
      return "text-emerald-400";
  }
};

const ProbRow = ({
  label,
  pct,
  verdict,
  verdictText,
}: {
  label: string;
  pct: number;
  verdict: Verdict;
  verdictText: string;
}) => (
  <div className="flex items-center gap-3">
    <span className="w-44 shrink-0 text-sm text-muted-foreground">{label}</span>
    <div className="flex-1">
      <div className="h-2 w-full overflow-hidden rounded-full bg-muted/40">
        <div
          className="h-full rounded-full bg-gradient-to-r from-primary to-secondary"
          style={{ width: `${Math.round(pct * 100)}%` }}
        />
      </div>
    </div>
    <span className={`w-36 shrink-0 text-right text-sm font-medium ${verdictColor(verdict)}`}>
      {verdictText} ({Math.round(pct * 100)}%)
    </span>
  </div>
);

const Block = ({
  title,
  icon: Icon,
  block,
  L,
}: {
  title: string;
  icon: typeof Activity;
  block: ProbBlock;
  L: typeof STRINGS.fr;
}) => (
  <Card className="border-primary/20 bg-card/60 backdrop-blur">
    <CardContent className="space-y-4 p-5">
      <div className="flex items-center gap-2 font-semibold">
        <Icon className="h-4 w-4 text-primary" />
        {title}
      </div>
      <div className="space-y-3">
        <ProbRow label={L.human} pct={block.human} verdict={block.humanVerdict} verdictText={L.verdicts[block.humanVerdict]} />
        <ProbRow label={L.hybrid} pct={block.hybrid} verdict={block.hybridVerdict} verdictText={L.verdicts[block.hybridVerdict]} />
        <ProbRow label={L.ai} pct={block.ai} verdict={block.aiVerdict} verdictText={L.verdicts[block.aiVerdict]} />
      </div>
    </CardContent>
  </Card>
);

const AISongChecker = () => {
  const { i18n } = useTranslation();
  const L = STRINGS[(i18n.language === "en" ? "en" : "fr") as "fr" | "en"];
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AISongCheckResult | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);

  const handleFile = useCallback(
    async (file?: File) => {
      if (!file) return;
      if (!isLikelyAudioFile(file)) {
        setError(L.invalid);
        return;
      }
      setError(null);
      setResult(null);
      setFileName(file.name);
      setIsAnalyzing(true);
      try {
        await new Promise((r) => setTimeout(r, 30));
        const r = await analyzeForAI(file);
        setResult(r);
      } catch (e) {
        console.error(e);
        setError(L.error);
      } finally {
        setIsAnalyzing(false);
      }
    },
    [L]
  );

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title={`${L.title} — Global Drip Studio`}
        description={L.tagline}
        path="/ai-song-checker"
        jsonLd={[
          softwareAppSchema({
            name: "AI Song Checker — Global Drip Studio",
            path: "/ai-song-checker",
            description: L.tagline,
            features: [
              "Analyse spectrale et temporelle locale",
              "Détection heuristique IA / Humain / Hybride",
              "100% navigateur, aucune upload",
            ],
          }),
          breadcrumbSchema([
            { name: "Home", path: "/" },
            { name: "AI Song Checker", path: "/ai-song-checker" },
          ]),
        ]}
      />
      <ToolkitHeader current={"aisong" as any} />

      <main className="container mx-auto px-4 py-8 sm:py-12">
        <Breadcrumbs items={[{ name: L.title, path: "/ai-song-checker" }]} />

        <div className="mx-auto max-w-3xl text-center">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs text-primary">
            <Sparkles className="h-3.5 w-3.5" /> Beta — heuristique
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            <Bot className="mr-2 inline h-7 w-7 text-primary" />
            {L.title}
          </h1>
          <p className="mt-3 text-muted-foreground">{L.tagline}</p>
        </div>

        <div className="mx-auto mt-8 max-w-3xl">
          {!result && !isAnalyzing && (
            <div
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragging(true);
              }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={(e) => {
                e.preventDefault();
                setIsDragging(false);
                handleFile(e.dataTransfer.files?.[0]);
              }}
              onClick={() => fileInputRef.current?.click()}
              className={`group cursor-pointer rounded-xl border-2 border-dashed p-12 text-center transition-colors ${
                isDragging ? "border-primary bg-primary/5" : "border-border bg-card/40 hover:border-primary/50"
              }`}
            >
              <Upload className="mx-auto mb-3 h-10 w-10 text-primary" />
              <p className="font-medium">{L.dropTitle}</p>
              <p className="mt-1 text-sm text-muted-foreground">{L.dropSub}</p>
              <input
                ref={fileInputRef}
                type="file"
                accept={AUDIO_ACCEPT}
                className="hidden"
                onChange={(e) => handleFile(e.target.files?.[0] ?? undefined)}
              />
            </div>
          )}

          {isAnalyzing && (
            <div className="flex flex-col items-center justify-center rounded-xl border border-border bg-card/40 p-12">
              <Loader2 className="h-10 w-10 animate-spin text-primary" />
              <p className="mt-3 text-sm text-muted-foreground">{L.analyzing}</p>
            </div>
          )}

          {error && (
            <div className="mt-4 flex items-center gap-2 rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
              <AlertTriangle className="h-4 w-4" />
              {error}
            </div>
          )}

          {result && !isAnalyzing && (
            <div className="space-y-5">
              <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-card/40 p-4">
                <div className="flex items-center gap-3">
                  <FileAudio className="h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">{fileName}</p>
                    <p className="text-xs text-muted-foreground">
                      {L.duration}: {result.durationSec.toFixed(1)} {L.seconds} · {result.sampleRate} Hz
                    </p>
                  </div>
                </div>
                <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()}>
                  <Upload className="mr-2 h-3.5 w-3.5" /> {L.analyze}
                </Button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept={AUDIO_ACCEPT}
                  className="hidden"
                  onChange={(e) => handleFile(e.target.files?.[0] ?? undefined)}
                />
              </div>

              <Block title={L.spectral} icon={BarChart3} block={result.spectral} L={L} />
              <Block title={L.temporal} icon={Activity} block={result.temporal} L={L} />
              <Block title={L.overall} icon={Sparkles} block={result.overall} L={L} />

              <Card className="border-border/60">
                <CardContent className="p-5">
                  <div className="mb-3 flex items-center gap-2 text-sm font-semibold">
                    <Info className="h-4 w-4 text-primary" /> {L.detailsTitle}
                  </div>
                  <div className="grid gap-2 text-sm sm:grid-cols-2">
                    {Object.entries(result.features).map(([k, v]) => (
                      <div key={k} className="flex items-center justify-between rounded border border-border/40 bg-muted/20 px-3 py-1.5">
                        <span className="text-muted-foreground">{L.features[k as keyof typeof L.features]}</span>
                        <span className="font-mono">
                          {typeof v === "number" ? (Math.abs(v) > 1000 ? v.toFixed(0) : v.toFixed(3)) : String(v)}
                        </span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm">
                <div className="mb-1 flex items-center gap-2 font-semibold text-primary">
                  <Info className="h-4 w-4" /> {L.disclaimerTitle}
                </div>
                <p className="text-muted-foreground">{L.disclaimer}</p>
              </div>
            </div>
          )}

          <div className="mt-10 text-center">
            <Link to="/" className="text-sm text-muted-foreground underline-offset-4 hover:underline">
              ← {i18n.language === "en" ? "Back home" : "Retour à l'accueil"}
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AISongChecker;
